import type { NextApiRequest, NextApiResponse } from 'next'

type SelectOption = {
    value: String,
    label: String
}

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<SelectOption[]>
) {
    res.status(200).json([
        {value:"1",label:"Al-Fatihah(The Opening)"},
        {value:"2",label:"Al-Baqarah(The Cow)"},
        {value:"3",label:"Al-‘Imran(The Family of Amran)"},
        {value:"4",label:"An-Nisa’(The Women)"},
        {value:"5",label:"Al-Ma’idah(The Food)"},
        {value:"6",label:"Al-An’am(The Cattle)"},
        {value:"7",label:"Al-A’raf(The Elevated Places)"},
        {value:"8",label:"Al-Anfal(Voluntary Gifts)"},
        {value:"9",label:"Al-Bara’at / At-Taubah(The Immunity)"},
        {value:"10",label:"Yunus(Jonah)"},
        {value:"11",label:"Hud(Hud)"},
        {value:"12",label:"Yusuf(Joseph)"},
        {value:"13",label:"Ar-Ra’d(The Thunder)"},
        {value:"14",label:"Ibrahim(Abraham)"},
        {value:"15",label:"Al-Hijr(The Rock)"},
        {value:"16",label:"An-Nahl(The Bee)"},
        {value:"17",label:"Bani Isra’il(The Israelites)"},
        {value:"18",label:"Al-Kahf(The Cave)"},
        {value:"19",label:"Maryam(Mary)"},
        {value:"20",label:"Ta Ha(Ta Ha)"},
        {value:"21",label:"Al-Anbiya’(The Prophets)"},
        {value:"22",label:"Al-Hajj(The Pilgrimage)"},
        {value:"23",label:"Al-Mu’minun(The Believers)"},
        {value:"24",label:"An-Nur(The Light)"},
        {value:"25",label:"Al-Furqan(The Discrimination)"},
        {value:"26",label:"Ash-Shu’ara’(The Poets)"},
        {value:"27",label:"An-Naml(The Naml)"},
        {value:"28",label:"Al-Qasas(The Narrative)"},
        {value:"29",label:"Al-‘Ankabut(The Spider)"},
        {value:"30",label:"Ar-Rum(The Romans)"},
        {value:"31",label:"Luqman(Luqman)"},
        {value:"32",label:"As-Sajdah(The Adoration)"},
        {value:"33",label:"Al-Ahzab(The Allies)"},
        {value:"34",label:"Al-Saba’(The Saba’)"},
        {value:"35",label:"Al-Fatir(The Originator)"},
        {value:"36",label:"Ya Sin(Ya Sin)"},
        {value:"37",label:"As-Saffat(Those Ranging in Ranks)"},
        {value:"38",label:"Sad(Sad)"},
        {value:"39",label:"Az-Zumar(The Companies)"},
        {value:"40",label:"Al-Mu’min(The Believer)"},
        {value:"41",label:"Ha Mim(Ha Mim)"},
        {value:"42",label:"Ash-Shura(Counsel)"},
        {value:"43",label:"Az-Zukhruf(Gold)"},
        {value:"44",label:"Ad-Dukhan(The Drought)"},
        {value:"45",label:"Al-Jathiyah(The Kneeling)"},
        {value:"46",label:"Al-Ahqaf(The Sandhills)"},
        {value:"47",label:"Muhammad(Muhammad)"},
        {value:"48",label:"Al-Fath(The Victory)"},
        {value:"49",label:"Al-Hujurat(The Apartments)"},
        {value:"50",label:"Qaf(Qaf)"},
        {value:"51",label:"Ad-Dhariyat(The Scatterers)"},
        {value:"52",label:"At-Tur(The Mountain)"},
        {value:"53",label:"An-Najm(The Star)"},
        {value:"54",label:"Al-Qamar(The Moon)"},
        {value:"55",label:"Ar-Rahman(The Beneficent)"},
        {value:"56",label:"Al-Waqi’ah(The Event)"},
        {value:"57",label:"Al-Hadid(Iron)"},
        {value:"58",label:"Al-Mujadilah(The Pleading Woman)"},
        {value:"59",label:"Al-Hashr(The Banishment)"},
        {value:"60",label:"Al-Mumtahanah(The Woman who is Examined)"},
        {value:"61",label:"As-Saff(The Ranks)"},
        {value:"62",label:"Al-Jumu’ah(The Congregation)"},
        {value:"63",label:"Al-Munafiqun(The Hypocrites)"},
        {value:"64",label:"At-Taghabun(The Manifestation of Losses)"},
        {value:"65",label:"At-Talaq(Divorce)"},
        {value:"66",label:"At-Tahrim(The Prohibition)"},
        {value:"67",label:"Al-Mulk(The Kingdom)"},
        {value:"68",label:"Al-Qalam(The Pen)"},
        {value:"69",label:"Al-Haqqah(The Sure Truth)"},
        {value:"70",label:"Al-Ma’arij(The Ways of Ascent)"},
        {value:"71",label:"Nuh(Noah)"},
        {value:"72",label:"Al-Jinn(The Jinn)"},
        {value:"73",label:"Al-Muzzammil(The One Covering Himself)"},
        {value:"74",label:"Al-Muddaththir(The One Wrapping Himself Up)"},
        {value:"75",label:"Al-Qiyamah(The Resurrection)"},
        {value:"76",label:"Al-Insan(The Man)"},
        {value:"77",label:"Al-Mursalat(Those Sent Forth)"},
        {value:"78",label:"An-Naba’(The Announcement)"},
        {value:"79",label:"An-Nazi’at(Those Who Yearn)"},
        {value:"80",label:"‘Abasa(He Frowned)"},
        {value:"81",label:"At-Takwir(The Folding Up)"},
        {value:"82",label:"Al-Infitar(The Cleaving)"},
        {value:"83",label:"At-Tatfif(Default in Duty)"},
        {value:"84",label:"Al-Inshiqaq(The Bursting Asunder)"},
        {value:"85",label:"Al-Buruj(The Stars)"},
        {value:"86",label:"At-Tariq(The Comer by Night)"},
        {value:"87",label:"Al-A’la(The Most High)"},
        {value:"88",label:"Al-Ghashiyah(The Overwhelming Event)"},
        {value:"89",label:"Al-Fajr(The Daybreak)"},
        {value:"90",label:"Al-Balad(The City)"},
        {value:"91",label:"Ash-Shams(The Sun)"},
        {value:"92",label:"Al-Lail(The Night)"},
        {value:"93",label:"Ad-Duha(The Brightness of the Day)"},
        {value:"94",label:"Al-Inshirah(The Expansion)"},
        {value:"95",label:"At-Tin(The Fig)"},
        {value:"96",label:"Al-‘Alaq(The Clot)"},
        {value:"97",label:"Al-Qadr(The Majesty)"},
        {value:"98",label:"Al-Bayyinah(The Clear Evidence)"},
        {value:"99",label:"Al-Zilzal(The Shaking)"},
        {value:"100",label:"Al-‘Adiyat(The Assaulters)"},
        {value:"101",label:"Al-Qari’ah(The Calamity)"},
        {value:"102",label:"At-Takathur(The Abundance of Wealth)"},
        {value:"103",label:"Al-‘Asr(The Time)"},
        {value:"104",label:"Al-Humazah(The Slanderer)"},
        {value:"105",label:"Al-Fil(The Elephant)"},
        {value:"106",label:"Al-Quraish(The Quraish)"},
        {value:"107",label:"Al-Ma’un(Acts of Kindness)"},
        {value:"108",label:"Al-Kauthar(The Abundance of Good)"},
        {value:"109",label:"Al-Kafirun(The Disbelievers)"},
        {value:"110",label:"An-Nasr(The Help)"},
        {value:"111",label:"Al-Lahab(The Flame)"},
        {value:"112",label:"Al-Ikhlas(The Unity)"},
        {value:"113",label:"Al-Falaq(The Dawn)"},
        {value:"114",label:"An-Nas(The Men)"},
    ])
}
